import { createFileRoute, Link } from "@tanstack/react-router";
import { Box, Expand, Rotate3D } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ProductCard, SectionHeading } from "@/components/site/Storefront";
import { archiveImage, products, telegraphImage } from "@/lib/catalog";

export const Route=createFileRoute("/collectibles/telegraph")({head:()=>({meta:[{title:"Electromagnetic Telegraph, 1840 — The Patent Archive"},{name:"description",content:"Explore Samuel Morse's electromagnetic telegraph through its model, drawings, history, and inspired editions."},{property:"og:title",content:"Electromagnetic Telegraph, 1840 — The Patent Archive"},{property:"og:description",content:"Explore Samuel Morse's electromagnetic telegraph through its model, drawings, history, and inspired editions."},{property:"og:type",content:"article"},{name:"twitter:card",content:"summary_large_image"}]}),component:Story});
function Story(){return <><section className="section-shell py-10"><div className="mb-7 flex items-center gap-2 text-xs text-muted-foreground"><Link to="/">Archive</Link><span>/</span><span>Communications</span><span>/</span><strong className="text-foreground">The Telegraph</strong></div><div className="grid gap-8 lg:grid-cols-[1.35fr_.65fr]"><div className="grid gap-3 sm:grid-cols-2"><img src={telegraphImage} width="1408" height="1008" alt="Electromagnetic telegraph patent model" className="aspect-square size-full object-cover sm:col-span-2"/><img src={archiveImage} width="1408" height="1008" alt="Telegraph patent drawings and archive materials" className="aspect-[4/3] size-full object-cover"/><div className="relative flex aspect-[4/3] flex-col items-center justify-center bg-primary text-primary-foreground"><Rotate3D className="size-12 text-primary-foreground/50"/><p className="mt-5 font-display text-2xl">Interactive 3D Model</p><span className="mt-2 text-xs text-primary-foreground/50">Drag to rotate · Scroll to zoom</span><Expand className="absolute right-4 top-4 size-4"/></div></div><aside className="lg:sticky lg:top-28 lg:self-start"><p className="fine-label text-accent">Patent model · Communications</p><h1 className="mt-4 text-5xl leading-[.95] sm:text-6xl">Electromagnetic Telegraph</h1><p className="mt-5 font-display text-2xl italic text-ink-soft">Samuel F. B. Morse</p><dl className="mt-8 divide-y divide-border border-y border-border">{[["Patent number","US 1,647"],["Year granted","1840"],["Material","Brass, copper & walnut"],["Archive number","PA-COM-004"]].map(([a,b])=><div className="flex justify-between py-4 text-sm" key={a}><dt className="text-muted-foreground">{a}</dt><dd className="font-semibold">{b}</dd></div>)}</dl><p className="mt-7 leading-7 text-muted-foreground">A precise working model of the apparatus that made near-instant communication possible across great distances.</p><Button variant="museum" size="lg" className="mt-7 w-full">View inspired editions</Button></aside></div></section>
<section className="border-y border-border bg-parchment py-20"><div className="section-shell grid gap-12 lg:grid-cols-[.65fr_1.35fr]"><div><p className="fine-label text-accent">Historical story</p><h2 className="mt-4 text-5xl">When the world began to speak in signals</h2><p className="mt-6 font-display text-2xl italic text-ink-soft">“What hath God wrought?”</p></div><div className="columns-1 gap-10 text-base leading-8 text-muted-foreground md:columns-2"><p>Before the telegraph, information traveled only as fast as a person, horse, or ship could carry it. Samuel Morse’s system separated language from physical transport, encoding words into electrical impulses that could race along a wire.</p><p className="mt-5 md:mt-0">The first public demonstration in 1844 linked Washington and Baltimore. In a moment, distance took on a new meaning. Commerce, journalism, diplomacy, and daily life were fundamentally recast.</p><p className="mt-5">This patent model reveals the physical intelligence behind the breakthrough: coils convert electricity into motion, moving an armature that marks the coded signal. Its quiet precision helped inaugurate the information age.</p></div></div></section>
<section className="section-shell py-20"><SectionHeading eyebrow="Inside the invention" title="Drawings, details, and related ideas"/><div className="grid gap-5 md:grid-cols-3"><img src={archiveImage} alt="Patent archive" className="aspect-[4/3] size-full object-cover md:col-span-2"/><div className="flex flex-col justify-between bg-primary p-7 text-primary-foreground"><Box className="size-6 text-primary-foreground/45"/><div><p className="fine-label text-primary-foreground/45">Related invention</p><h3 className="mt-3 text-3xl">Printing Telegraph</h3><p className="mt-3 text-sm leading-6 text-primary-foreground/60">The next chapter in making electrical messages more immediate and legible.</p></div></div></div></section>
<section className="bg-gallery py-20"><div className="section-shell"><SectionHeading eyebrow="Inspired by the telegraph" title="Shop products from this collectible"/><div className="grid grid-cols-2 gap-x-5 gap-y-10 lg:grid-cols-4">{products.slice(0,8).map(p=><ProductCard key={p.name} product={p}/>)}</div></div></section></>}